### ISSUE TITLE
Heap space

### ISSUE THREAD

**Issue by richymelero** [tabulapdf/tabula#1115]
2020-03-27 17:51:17.768:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@68f7aae2{/,file:/C:/Users/richy/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1023459508760612379.dir/webapp/,AVAILABLE}{file:/C:/Users/richy/dev/tabula/tabula.jar}
2020-03-27 17:51:17.772:WARN:oejsh.RequestLogHandler:main: !RequestLog
2020-03-27 17:51:17.814:INFO:oejs.ServerConnector:main: Started ServerConnector@74eec640{HTTP/1.1}{0.0.0.0:8080}
2020-03-27 17:51:17.815:INFO:oejs.Server:main: Started @32877ms
2020-03-27 17:52:06.583:WARN:oejs.ServletHandler:qtp2046562095-18: Error for /documents
java.lang.OutOfMemoryError: Java heap space
        at org.jruby.util.ByteList.ensure(ByteList.java:341)
        at org.jruby.util.io.EncodingUtils$1.resize(EncodingUtils.java:1197)
        at org.jruby.util.io.EncodingUtils.moreOutputBuffer(EncodingUtils.java:1513)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1415)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1312)
        at org.jruby.util.io.EncodingUtils.strTranscode0(EncodingUtils.java:936)
        at org.jruby.util.io.EncodingUtils.strTranscode(EncodingUtils.java:857)
        at org.jruby.util.io.EncodingUtils.strEncode(EncodingUtils.java:829)
        at org.jruby.RubyString.encode(RubyString.java:5398)
        at json.ext.Parser.convertEncoding(Parser.java:196)
        at json.ext.Parser.initialize(Parser.java:175)
        at json.ext.Parser$INVOKER$i$0$1$initialize.call(Parser$INVOKER$i$0$1$initialize.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:725)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:741)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:278)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:79)
        at org.jruby.RubyObject.callInit(RubyObject.java:348)
        at json.ext.Parser.newInstance(Parser.java:151)
        at json.ext.Parser$INVOKER$s$0$1$newInstance.call(Parser$INVOKER$s$0$1$newInstance.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
mar 27, 2020 5:52:08 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTask)
        at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:302)
        at RUBY.afterExecute(C:/Users/richy/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1023459508760612379.dir/webapp/WEB-INF/lib/tabula_job_executor/executor.rb:42)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.java.util.concurrent.ThreadPoolExecutor$Proxy1.afterExecute(org/jruby/proxy/java/util/concurrent/ThreadPoolExecutor$Proxy1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor$Worker)
        at java.lang.Thread.run(java/lang/Thread)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.jruby.util.ByteList.ensure(ByteList.java:341)
        at org.jruby.util.io.EncodingUtils$1.resize(EncodingUtils.java:1197)
        at org.jruby.util.io.EncodingUtils.moreOutputBuffer(EncodingUtils.java:1513)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1415)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1312)
        at org.jruby.util.io.EncodingUtils.strTranscode0(EncodingUtils.java:936)
        at org.jruby.util.io.EncodingUtils.strTranscode(EncodingUtils.java:857)
        at org.jruby.util.io.EncodingUtils.strEncode(EncodingUtils.java:829)
        at org.jruby.RubyString.encode(RubyString.java:5398)
        at json.ext.Parser.convertEncoding(Parser.java:196)
        at json.ext.Parser.initialize(Parser.java:175)
        at json.ext.Parser$INVOKER$i$0$1$initialize.call(Parser$INVOKER$i$0$1$initialize.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:725)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:741)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:77)
        at org.jruby.RubyObject.callInit(RubyObject.java:348)
        at json.ext.Parser.newInstance(Parser.java:151)
        at json.ext.Parser$INVOKER$s$0$1$newInstance.call(Parser$INVOKER$s$0$1$newInstance.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:181)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:153)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTask)
        at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:302)
        at RUBY.afterExecute(C:/Users/richy/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1023459508760612379.dir/webapp/WEB-INF/lib/tabula_job_executor/executor.rb:42)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.java.util.concurrent.ThreadPoolExecutor$Proxy1.afterExecute(org/jruby/proxy/java/util/concurrent/ThreadPoolExecutor$Proxy1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor$Worker)
        at java.lang.Thread.run(java/lang/Thread)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.jruby.util.ByteList.ensure(ByteList.java:341)
        at org.jruby.util.io.EncodingUtils$1.resize(EncodingUtils.java:1197)
        at org.jruby.util.io.EncodingUtils.moreOutputBuffer(EncodingUtils.java:1513)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1415)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1312)
        at org.jruby.util.io.EncodingUtils.strTranscode0(EncodingUtils.java:936)
        at org.jruby.util.io.EncodingUtils.strTranscode(EncodingUtils.java:857)
        at org.jruby.util.io.EncodingUtils.strEncode(EncodingUtils.java:829)
        at org.jruby.RubyString.encode(RubyString.java:5398)
        at json.ext.Parser.convertEncoding(Parser.java:196)
        at json.ext.Parser.initialize(Parser.java:175)
        at json.ext.Parser$INVOKER$i$0$1$initialize.call(Parser$INVOKER$i$0$1$initialize.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:725)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:741)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:77)
        at org.jruby.RubyObject.callInit(RubyObject.java:348)
        at json.ext.Parser.newInstance(Parser.java:151)
        at json.ext.Parser$INVOKER$s$0$1$newInstance.call(Parser$INVOKER$s$0$1$newInstance.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:181)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:153)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
mar 27, 2020 5:52:34 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:34 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:34 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:35 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:35 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:36 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:38 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:38 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:39 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:39 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:41 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:42 PM org.apache.pdfbox.pdmodel.font.PDCIDFontType2 <init>
INFORMACI├ôN: OpenType Layout tables used in font ABCDEE+Calibri are not implemented in PDFBox and will be ignored
mar 27, 2020 5:52:42 PM org.apache.pdfbox.cos.COSDocument finalize
ADVERTENCIA: Warning: You did not close a PDF Document

**Comment by richymelero** [comment]
Solved deleting the directory C:\Users\richy\AppData\Roaming\Tabula

**Comment by nahumbb** [comment]
Thanks @richymelero for the tip. Solved for me as well!
