### ISSUE TITLE
Error reading file

### ISSUE THREAD

**Issue by glancia** [tabulapdf/tabula#1158]
Dear all,

I'm getting the following error when running this (both pdf and template attached). I'm getting error both on command line and web application. I cannot figure out what could be.

Web app
![image](https://user-images.githubusercontent.com/26585392/88240700-497ad400-cc5e-11ea-8387-903fddf5a56e.png)

Command
```
java -jar /tabula/tabula-1.0.3-jar-with-dependencies.jar -t -p 1 -f JSON  -a 236.24999048578465,171.14172744750977,254.8523521648618,258.9448745727539    -o '/tmp/invoice2json.json' '/invoices/inbox/zzJHcbwB_0_pxgt jul.pdf'
```

error
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at technology.tabula.extractors.BasicExtractionAlgorithm.columnPositions(BasicExtractionAlgorithm.java:114)
	at technology.tabula.extractors.BasicExtractionAlgorithm.extract(BasicExtractionAlgorithm.java:63)
	at technology.tabula.CommandLineApp$TableExtractor.extractTablesBasic(CommandLineApp.java:416)
	at technology.tabula.CommandLineApp$TableExtractor.extractTables(CommandLineApp.java:390)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:175)
	at technology.tabula.CommandLineApp.extractFileInto(CommandLineApp.java:143)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:133)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:109)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:79)

```

template
```
[{"page":1,"extraction_method":"stream","selection_id":"T1595461771184","x1":171.14172744750977,"x2":258.9448745727539,"y1":236.24999048578465,"y2":254.8523521648618,"width":87.8,"height": 18.6,"spec_index":0}]
```

[zzJHcbwB_0_pxgt jul.pdf](https://github.com/tabulapdf/tabula/files/4963258/zzJHcbwB_0_pxgt.jul.pdf)

**Comment by JohnTurgeson** [comment]
I get roughly the same issue when running my own Java application using the tabula JAR. Stack looks like:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at technology.tabula.extractors.BasicExtractionAlgorithm.columnPositions(BasicExtractionAlgorithm.java:119)
	at technology.tabula.extractors.BasicExtractionAlgorithm.extract(BasicExtractionAlgorithm.java:63)
	at Main$TableExtractor.extractTablesBasic(Main.java:357)
	at Main$TableExtractor.extractTables(Main.java:339)
	at Main.Parse(Main.java:100)
	at Main.processPDF(Main.java:216)
	at Main.main(Main.java:153)

And I've traced the offending line to:

BaicExtractionAlgorithm.java:

        List<Rectangle> regions = new ArrayList<Rectangle>();
        for (TextChunk tc: lines.get(0).getTextElements()) {                 <----- This array access when the list is empty!
            if (tc.isSameChar(Line.WHITE_SPACE_CHARS)) { 

I also attached a small snapshot of the offending pdf. Basically there's an engine schematic and a bunch of numbers to label components with the numbers having lines to the component:

![image](https://user-images.githubusercontent.com/1203101/88414980-b9e33b80-cdab-11ea-893b-0d48861a8647.png)

**Comment by glancia** [comment]
Any clue on how I can avoid the error to stop the program?

**Comment by JohnTurgeson** [comment]
I just catch the exception, skip the "table" and move on.
