### ISSUE TITLE
Issue after clicking on download all data with multiple tables selected

### ISSUE THREAD

**Issue by anchapin** [tabulapdf/tabula#272]
Here is the error code:

```
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
      http://127.0.0.1:8080/pdf/ed0a4fe386ca590133e920bcd1beabc513125aba/data<br /><br />(ArgumentError) comparison of Float with nil failed
```

Can you tell me how to upload the pdf?

**Comment by jeremybmerrill** [comment]
Are you running the latest version of Tabula? If not, please download [version 0.9.7](https://github.com/tabulapdf/tabula/releases/tag/v0.9.7).

If you are, I think you've found a bug we haven't seen before. If the PDF isn't sensitive, could you send it to me? (Preferably as a link, or as an attachment to an email to me directly -- Github doesn't support PDF uploads.) I'll need the PDF to try to replicate the issue.

**Comment by jeremybmerrill** [comment]
Someone else has the same issue with [this pdf](http://transition.fcc.gov/Daily_Releases/Daily_Business/2015/db0130/DA-15-131A2.pdf):
```
ArgumentError: comparison of Float with nil failed
	org/jruby/RubyFloat.java:615:in `<'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:296:in `snap_points!'
	org/jruby/RubyArray.java:1613:in `each'
	org/jruby/RubyEnumerable.java:865:in `inject'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:293:in `snap_points!'
	org/jruby/RubyArray.java:1613:in `each'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:290:in `snap_points!'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:218:in `get_ruling_lines!'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:204:in `horizontal_ruling_lines'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:41:in `minimal_bounding_box_of_ruling_lines'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:25:in `initialize'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/entities/page.rb:85:in `get_area'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/tabula-extractor-0.7.6-java/lib/tabula/table_extractor.rb:82:in `extract_table'
	/Users/204434/code/tabula/webapp/tabula_web.rb:234:in `(root)'
	org/jruby/RubyArray.java:1613:in `each'
	org/jruby/RubyEnumerable.java:977:in `each_with_index'
	org/jruby/RubyEnumerator.java:274:in `each'
	org/jruby/RubyEnumerable.java:763:in `map'
	/Users/204434/code/tabula/webapp/tabula_web.rb:233:in `(root)'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:0:in `on'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:200:in `try'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:161:in `on'
	/Users/204434/code/tabula/webapp/tabula_web.rb:214:in `(root)'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:0:in `on'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:200:in `try'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:161:in `on'
	/Users/204434/code/tabula/webapp/tabula_web.rb:160:in `(root)'
	org/jruby/RubyBasicObject.java:1533:in `instance_eval'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:127:in `call!'
	org/jruby/RubyKernel.java:1270:in `catch'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:126:in `call!'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:111:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/reloader.rb:44:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/static.rb:119:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/cuba-3.3.0/lib/cuba.rb:74:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/1.9/webrick/httpserver.rb:138:in `service'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/1.9/webrick/httpserver.rb:94:in `run'
	/Users/204434/.rbenv/versions/jruby-1.7.19/lib/ruby/1.9/webrick/server.rb:191:in `start_thread'
```

**Comment by jeremybmerrill** [comment]
Inspecting text elements as they're created out of PDFBox, they're getting reported with width/height of 0. 

```
...
#<TextElement: 525.52,496.86,525.52,496.86 '7'>
#<TextElement: 525.52,496.86,525.52,496.86 '0'>
#<TextElement: 525.52,496.86,525.52,496.86 '7'>
#<TextElement: 525.52,496.86,525.52,496.86 '4'>
#<TextElement: 525.52,620.62,525.52,620.62 '$'>
#<TextElement: 525.52,620.62,525.52,620.62 ' '>
#<TextElement: 525.52,620.62,525.52,620.62 '6'>
#<TextElement: 525.52,620.62,525.52,620.62 '1'>
#<TextElement: 525.52,620.62,525.52,620.62 '0'>
#<TextElement: 525.52,620.62,525.52,620.62 ','>
...
````

x and y are also incorrect -- if I artificially set a width and a height, we end up with shuffled gibberish:

![screenshot from 2015-02-25 21 00 19](https://cloud.githubusercontent.com/assets/548250/6384934/62ab5356-bd31-11e4-953f-fb604c6169c7.png)

@jazzido: you've had success reporting PDFBox bugs, yeah? What's the process like?

**Comment by jazzido** [comment]
Maybe it's time to retire `tabula-extractor` and focus on getting `tabula-java` ready. Works great and fast (2.7s including JVM startup):

```
time java -jar target/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar --area 172.84,19.54,533.96,776.99 -p 1 ~/Downloads/a.pdf
Feb 25, 2015 9:10:10 PM org.apache.pdfbox.pdmodel.graphics.xobject.PDXObjectImage mask
WARNING: Colour key masking isn't supported
"AW-BEA001-A1 ","Bangor ME 255 ",,"Northstar Wireless, LLC ","0023917453 ","$ 36,000.00 ","$ 27,000.0"
"",,,,,,
"AW-BEA001-B1 ","Bangor ME 254 ",,"SNR Wireless LicenseCo, LLC ","0023907074 ","$ 341,000.00 ","$ 255,750.0"
"",,,,,,
"AW-BEA001-H ","Bangor ME 169 ",,"Advantage Spectrum, L.P. ","0023909104 ","$ 2,500,000.00 ","$ 1,875,000.0"
"",,,,,,
"AW-BEA001-I ","Bangor ME 167 ",,"Advantage Spectrum, L.P. ","0023909104 ","$ 2,149,000.00 ","$ 1,611,750.0"
"",,,,,,
"AW-BEA001-J ","Bangor ME 163 ",,"AT&T Wireless Services 3 LLC ","0023910920 ","$ 4,416,000.00 ","$ 4,416,000.0"
"",,,,,,
"AW-BEA002-A1 ","Portland ME 245 ",,"Northstar Wireless, LLC ","0023917453 ","$ 245,000.00 ","$ 183,750.0"
"",,,,,,
"AW-BEA002-B1 ","Portland ME 190 ",,"SNR Wireless LicenseCo, LLC ","0023907074 ","$ 750,000.00 ","$ 562,500.0"
"",,,,,,
"AW-BEA002-H ","Portland ME 29 ",,"Advantage Spectrum, L.P. ","0023909104 ","$ 4,319,000.00 ","$ 3,239,250.0"
"",,,,,,
"AW-BEA002-I ","Portland ME 29 ",,"Advantage Spectrum, L.P. ","0023909104 ","$ 7,417,000.00 ","$ 5,562,750.0"
"",,,,,,
"AW-BEA002-J ","Portland ME 30 ",,"AT&T Wireless Services 3 LLC ","0023910920 ","$ 22,346,000.00 ","$ 22,346,000.0"
"",,,,,,
"AW-BEA003-A1 ","Boston-Worcester MA-NH-RI-VT 87 ",,"Tristar License Group, LLC ","0023907975 ","$ 5,458,000.00 ","$ 4,093,500.0"
"",,,,,,
"AW-BEA003-B1 ","Boston-Worcester MA-NH-RI-VT 239 ",,"Northstar Wireless, LLC ","0023917453 ","$ 97,788,000.00 ","$ 73,341,000.0"
"",,,,,,
"AW-BEA003-H ","Boston-Worcester MA-NH-RI-VT 21 ",,"Northstar Wireless, LLC ","0023917453 ","$ 233,899,000.00 ","$ 175,424,250.0"
"",,,,,,
"AW-BEA003-I ","Boston-Worcester MA-NH-RI-VT 21 ",,"Northstar Wireless, LLC ","0023917453 ","$ 234,451,000.00 ","$ 175,838,250.0"
"",,,,,,
"AW-BEA003-J ","Boston-Worcester MA-NH-RI-VT 27 ",,"AT&T Wireless Services 3 LLC ","0023910920 ","$ 596,573,000.00 ","$ 596,573,000.0"
"",,,,,,
"AW-BEA004-A1 ","Burlington VT-NY 21 ",,"SNR Wireless LicenseCo, LLC ","0023907074 ","$ 89,000.00 ","$ 66,750.0"
"",,,,,,
"AW-BEA004-B1 ","Burlington VT-NY 122 ",,"SNR Wireless LicenseCo, LLC ","0023907074 ","$ 610,000.00 ","$ 457,500.0"
java -jar target/tabula-extractor-0.7.4-SNAPSHOT-jar-with-dependencies.jar     2.69s user 0.15s system 125% cpu 2.270 total
```

**Comment by jazzido** [comment]
Re: reporting bugs to PDFBox — Current `tabula-extractor` is using a `SNAPSHOT` version of PDFBox, so that might be it. In `tabula-java` I chose to go back to a stable version.

In any case, `TextElement` is a Tabula class, not a PDFBox class. Let's make sure that we're not screwing up when creating `TextElement`s from PDFBox objects.

**Comment by jeremybmerrill** [comment]
I inspected them pretty immediately, even before it goes into TextElement 
```
        puts [text.getWidthDirAdj, text.getHeightDir].inspect
```
(extraction.rb, 274)

and still got zeroes for both. It's gotta be in PDFBox, I think...

**Comment by jeremybmerrill** [comment]
No pref between tabula-extractor and tabula-java. There's nothign on my list that I plan on doing in tabula-extractor, but the UI stuff is higher priority for me.

**Comment by jazzido** [comment]
I've just built `pdfbox-2.0.0-SNAPSHOT` against the latest `trunk`: http://dump.jazzido.com/pdfbox-app-2.0.0-SNAPSHOT.jar — Can you replace it in `tabula-extractor` and test? (Sorry, I don't have the build env ready on the box I'm now)

**Comment by jeremybmerrill** [comment]
Won't start up: 

```
NameError: missing class or uppercase package name (`org.apache.pdfbox.util.TextPosition'), caused by (NameError) cannot load Java class org.apache.pdfbox.util.TextPosition
  get_proxy_or_package_under_package at org/jruby/javasupport/JavaUtilities.java:54
```

This new version is 7.2 mb where the old one was 11.6. Missing a dependency or something?

**Comment by jazzido** [comment]
Hrm, they probably changed the API. Can you try with the newest `stable`? http://www.gtlib.gatech.edu/pub/apache//pdfbox/1.8.8/pdfbox-app-1.8.8.jar

**Comment by jazzido** [comment]
Just tried it myself. Don't even bother. A lot of the current `tabula-extractor` is tuned to *some* revision of PDFBox `trunk`. Bad decision on my part :( — I guess we're stuck with it for now.

**Comment by anchapin** [comment]
Thanks for the quick response. I am attaching the redacted version of the
pdf (I removed the sensitive information which wasn't included in the
tables that I was using Tabula for).


Alex Chapin
about.me/anchapin
[image: Alex Chapin on about.me]
  <http://about.me/anchapin>

**Comment by jeremybmerrill** [comment]
Nope, @anchapin, you've got to email the PDF *directly* to me (jeremybmerrill  at jeremybmerrill dot com) -- GitHub strips out attachments.

**Comment by jeremybmerrill** [comment]
@anchapin If you're still interested in us looking into how to extract this PDF, please email the PDF directly to me (jeremybmerrill at jeremybmerrill dot com). 

Will reopen ticket when I get the PDF.
