### ISSUE TITLE
Can not run on Fedora 21, multiple Java errors

### ISSUE THREAD

**Issue by rlh100** [tabulapdf/tabula#399]
when I try to run tabula 1.0 I get the following errors:
When I run it at myself I get:
2015-09-13 20:27:46.728:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:8080: java.net.BindException: Address already in use

This probably is a SELinix issue.

So I ran it as root:sudo java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -jar tabula.jar
And I get the error:
ERROR: initialization failed
org.jruby.rack.RackInitializationException: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

I am running fedora21:
uname -a
Linux science.cloud5.harker.com 4.0.4-202.fc21.x86_64 #1 SMP Wed May 27 22:28:42
cat /etc/redhat-release 
Fedora release 21 (Twenty One)

I am not running Oracle Java:
java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

Do I need to download the Oracle version?

===== Debug running as myself =====
java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -jar tabula.jar
2015-09-13 20:27:34.673:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-09-13 20:27:34.737:INFO:oejw.WebInfConfiguration:Extract jar:file:/home/harker/OpenData/WorkData/Budget/Budget-15-17.tabula/tabula/tabula.jar!/ to /tmp/warbler2798610645780659396webroot/tabula.jar/work/jetty-0.0.0.0-8080-tabula.jar-_-any-/webapp
INFO: jruby 1.7.15 (1.9.3p392) 2014-09-03 82b5cc3 on OpenJDK 64-Bit Server VM 1.8.0_45-b14 +jit [linux-amd64]
INFO: using a shared (threadsafe!) runtime
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DATA_DIR = /home/harker/.tabula
DOCUMENTS_BASEPATH = /home/harker/.tabula/pdfs
ENABLE_DEBUG_METHODS = false

======================================================
Launching web browser to http://127.0.0.1:34555

If it does not open in 10 seconds, you may manually open
a web browser to the above URL.
When you're done using the Tabula interface, you may
return to this window and press "Control-C" to close it.
======================================================

2015-09-13 20:27:46.668:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/,file:/tmp/warbler2798610645780659396webroot/tabula.jar/work/jetty-0.0.0.0-8080-tabula.jar-_-any-/webapp/},/home/harker/OpenData/WorkData/Budget/Budget-15-17.tabula/tabula/tabula.jar
2015-09-13 20:27:46.728:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:8080: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:182)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:260)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.Server.doStart(Server.java:274)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at JettyWarMain.main(JettyWarMain.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at WarMain.launchWebServer(WarMain.java:172)
	at WarMain.start(WarMain.java:346)
	at JarMain.doStart(JarMain.java:221)
	at WarMain.main(WarMain.java:369)
2015-09-13 20:27:46.729:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@53f0d09c: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:182)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:260)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.Server.doStart(Server.java:274)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at JettyWarMain.main(JettyWarMain.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at WarMain.launchWebServer(WarMain.java:172)
	at WarMain.start(WarMain.java:346)
	at JarMain.doStart(JarMain.java:221)
	at WarMain.main(WarMain.java:369)
error: java.lang.reflect.InvocationTargetException
error: java.lang.NullPointerException

===== Debug running as myself =====
sudo java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -jar tabula.jar
2015-09-13 20:35:26.122:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2015-09-13 20:35:26.150:INFO:oejw.WebInfConfiguration:Extract jar:file:/home/harker/OpenData/WorkData/Budget/Budget-15-17.tabula/tabula/tabula.jar!/ to /tmp/warbler1988619764964508635webroot/tabula.jar/work/jetty-0.0.0.0-8080-tabula.jar-_-any-/webapp
INFO: jruby 1.7.15 (1.9.3p392) 2014-09-03 82b5cc3 on OpenJDK 64-Bit Server VM 1.8.0_45-b14 +jit [linux-amd64]
INFO: using a shared (threadsafe!) runtime
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DATA_DIR = /root/.tabula
DOCUMENTS_BASEPATH = /root/.tabula/pdfs
ENABLE_DEBUG_METHODS = false

======================================================
Launching web browser to http://127.0.0.1:34555

If it does not open in 10 seconds, you may manually open
a web browser to the above URL.
When you're done using the Tabula interface, you may
return to this window and press "Control-C" to close it.
======================================================

ERROR: initialization failed
org.jruby.rack.RackInitializationException: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:31)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:764)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:406)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:756)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:242)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1221)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:699)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:454)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(Server.java:263)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at JettyWarMain.main(JettyWarMain.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at WarMain.launchWebServer(WarMain.java:172)
	at WarMain.start(WarMain.java:346)
	at JarMain.doStart(JarMain.java:221)
	at WarMain.main(WarMain.java:369)
Caused by: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(java/awt/Desktop.java:225)
	at java.awt.Desktop.browse(java/awt/Desktop.java:381)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
	at RUBY.(root)(/tmp/warbler1988619764964508635webroot/tabula.jar/work/jetty-0.0.0.0-8080-tabula.jar-_-any-/webapp/WEB-INF/config.ru:47)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1533)
	at RUBY.initialize(/tmp/warbler1988619764964508635webroot/tabula.jar/work/jetty-0.0.0.0-8080-tabula.jar-_-any-/webapp/WEB-INF/gems/gems/rack-1.5.2/lib/rack/builder.rb:55)
	at RUBY.(root)(/tmp/warbler1988619764964508635webroot/tabula.jar/work/jetty-0.0.0.0-8080-tabula.jar-_-any-/webapp/WEB-INF/config.ru:1)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(org/eclipse/jetty/server/handler/ContextHandler.java:764)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(org/eclipse/jetty/servlet/ServletContextHandler.java:406)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(org/eclipse/jetty/server/handler/ContextHandler.java:756)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(org/eclipse/jetty/servlet/ServletContextHandler.java:242)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(org/eclipse/jetty/webapp/WebAppContext.java:1221)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(org/eclipse/jetty/server/handler/ContextHandler.java:699)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(org/eclipse/jetty/webapp/WebAppContext.java:454)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(org/eclipse/jetty/server/handler/HandlerWrapper.java:90)
	at org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:263)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:59)
	at JettyWarMain.main(JettyWarMain.java:34)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
	... 4 more
2015-09-13 20:35:32.946:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/,file:/tmp/warbler1988619764964508635webroot/tabula.jar/work/jetty-0.0.0.0-8080-tabula.jar-_-any-/webapp/},/home/harker/OpenData/WorkData/Budget/Budget-15-17.tabula/tabula/tabula.jar
2015-09-13 20:35:32.974:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:8080: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:182)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:260)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.Server.doStart(Server.java:274)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at JettyWarMain.main(JettyWarMain.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at WarMain.launchWebServer(WarMain.java:172)
	at WarMain.start(WarMain.java:346)
	at JarMain.doStart(JarMain.java:221)
	at WarMain.main(WarMain.java:369)
2015-09-13 20:35:32.975:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@6f8e9d06: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:182)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:260)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at org.eclipse.jetty.server.Server.doStart(Server.java:274)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
	at JettyWarMain.main(JettyWarMain.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at WarMain.launchWebServer(WarMain.java:172)
	at WarMain.start(WarMain.java:346)
	at JarMain.doStart(JarMain.java:221)
	at WarMain.main(WarMain.java:369)
error: java.lang.reflect.InvocationTargetException
error: java.lang.NullPointerException

**Comment by mtigas** [comment]
@rlh100 Hi there, in 1.0 the frontend was attempting to use port 34555, but in the JAR version the underlying application was actually serving on port 8080.

First, can you update to [Tabula 1.0.1](https://github.com/tabulapdf/tabula/releases/tag/v1.0.1)?

Second, can you try using a port number other than 8080? Add the `-Dwarbler.port=9999` flag to your invocation, where 9999 is the port to try using. ([Instructions also here](https://github.com/tabulapdf/tabula/blob/v1.0.1/build/dist-README.txt#L34-L46).) The error you're seeing implies Java can't bind to port 8080 because something else is possibly listening on it already.
