### ISSUE TITLE
Use JBundler for managing the dependency with tabula-java

### ISSUE THREAD

**Issue by jazzido** [tabulapdf/tabula#418]
Use [JBundler](https://github.com/mkristian/jbundler) instead of storing the `tabula-java` jar in the repo.

(Depends on tabulapdf/tabula-java#38)

**Comment by jeremybmerrill** [comment]
I like this idea. I've been working on another project (the internal version of https://github.com/newsdev/stevedore) that's built/packaged like Tabula and would love to use JBundler if I could.

**Comment by jazzido** [comment]
I've been trying to implement this in [`fix/418`](https://github.com/tabulapdf/tabula/tree/fix/418) to no avail. Runs fine from `rackup` but complains if ran from a warbled jar:

```
java -jar build/tabula.jar
2015-11-03 19:58:55.026:INFO::main: Logging initialized @173ms
2015-11-03 19:58:55.036:INFO:oejr.Runner:main: Runner
2015-11-03 19:58:55.232:INFO:oejs.Server:main: jetty-9.2.9.v20150224
2015-11-03 19:59:04.472:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
INFO: jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_55-b13 +jit [darwin-x86_64]
INFO: using a shared (threadsafe!) runtime
An exception happened during JRuby-Rack startup
Could not find ruby-maven-libs-3.3.3 in any of the sources
--- System
jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_55-b13 +jit [darwin-x86_64]
Time: 2015-11-03 19:59:10 -0500
Server: jetty/9.2.9.v20150224
jruby.home: file:/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.22.jar!/META-INF/jruby.home

--- Context Init Parameters:
jruby.compat.version = 1.9
jruby.rack.logging = stderr
public.root = /
rack.env = production

--- Backtrace
Bundler::GemNotFound: Could not find ruby-maven-libs-3.3.3 in any of the sources
      materialize at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92
             map! at org/jruby/RubyArray.java:2446
      materialize at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85
            specs at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:140
        specs_for at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:185
  requested_specs at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:174
  requested_specs at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/environment.rb:18
            setup at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:13
            setup at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler.rb:127
           (root) at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/config.ru:3
    instance_eval at org/jruby/RubyBasicObject.java:1594
       initialize at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/builder.rb:55
           (root) at /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/config.ru:1

--- RubyGems
Gem.dir: /Users/manuel/.rvm/gems/jruby-1.7.22
Gem.path:
/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems
/Users/manuel/.rvm/gems/jruby-1.7.22
/Users/manuel/.rvm/gems/jruby-1.7.22@global
Activated gems:
  rack-1.6.4
  bundler-1.10.6

--- Bundler
Bundler.bundle_path: /Users/manuel/.rvm/gems/jruby-1.7.22
Bundler.root: /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF
Gemfile: /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/Gemfile
Settings:
  local.tabula-extractor = /Users/manuel/Work/tabula/tabula-extractor
  gemfile = /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/Gemfile
  without = development:test:assets
  jbundle_skip =

--- JRuby-Rack Config
compat_version = RUBY1_9
default_logger = org.jruby.rack.logging.StandardOutLogger@464ef2d7
equals = <error: >
err = java.io.PrintStream@449823a1
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size =
initial_runtimes =
jms_connection_factory =
jms_jndi_properties =
logger = org.jruby.rack.logging.OutputStreamLogger@604b4235
logger_class_name = stderr
logger_name = jruby.rack
maximum_memory_buffer_size =
maximum_runtimes =
num_initializer_threads =
out = java.io.PrintStream@2cec5a36
rackup =
rackup_path =
rewindable = true
runtime_arguments =
runtime_environment =
runtime_timeout_seconds =
serial_initialization = false
servlet_context = ServletContext@o.e.j.w.WebAppContext@1798b372{/,file:/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/,STARTING}{file:/Users/manuel/Work/tabula/tabula/build/tabula.jar}
throw_init_exception = false
ERROR: initialization failed
org.jruby.rack.RackInitializationException: Could not find ruby-maven-libs-3.3.3 in any of the sources
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `materialize'
	from org/jruby/RubyArray.java:2446:in `map!'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/config.ru:3:in `(root)'
	from org/jruby/RubyBasicObject.java:1594:in `instance_eval'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/config.ru:1:in `(root)'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at WarMain.launchWebServer(WarMain.java:181)
	at WarMain.start(WarMain.java:355)
	at JarMain.doStart(JarMain.java:228)
	at WarMain.main(WarMain.java:378)
Caused by: org.jruby.exceptions.RaiseException: (GemNotFound) Could not find ruby-maven-libs-3.3.3 in any of the sources
	at RUBY.materialize(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92)
	at org.jruby.RubyArray.map!(org/jruby/RubyArray.java:2446)
	at RUBY.materialize(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85)
	at RUBY.specs(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:140)
	at RUBY.specs_for(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:185)
	at RUBY.requested_specs(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:174)
	at RUBY.requested_specs(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/environment.rb:18)
	at RUBY.setup(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:13)
	at RUBY.setup(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler.rb:127)
	at RUBY.(root)(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/config.ru:3)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1594)
	at RUBY.initialize(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/gems/gems/rack-1.6.4/lib/rack/builder.rb:55)
	at RUBY.(root)(/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/WEB-INF/config.ru:1)
2015-11-03 19:59:10.878:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@1798b372{/,file:/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/,AVAILABLE}{file:/Users/manuel/Work/tabula/tabula/build/tabula.jar}
2015-11-03 19:59:10.879:WARN:oejsh.RequestLogHandler:main: !RequestLog
2015-11-03 19:59:10.896:INFO:oejs.ServerConnector:main: Started ServerConnector@1ea25a22{HTTP/1.1}{0.0.0.0:8080}
2015-11-03 19:59:10.897:INFO:oejs.Server:main: Started @16047ms
^CERROR: java.lang.NullPointerException
2015-11-03 20:17:27.194:INFO:oejs.ServerConnector:Thread-1: Stopped ServerConnector@1ea25a22{HTTP/1.1}{0.0.0.0:8080}
2015-11-03 20:17:27.208:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@1798b372{/,file:/private/var/folders/s7/25xbz7gd1v7fvz6zk9rf47gh0000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-5792510509507276501.dir/webapp/,UNAVAILABLE}{file:/Users/manuel/Work/tabula/tabula/build/tabula.jar}
```
