### ISSUE TITLE
Fails to start on linux with XDG_DATA_HOME set

### ISSUE THREAD

**Issue by olejorgenb** [tabulapdf/tabula#426]
```
$ java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -jar tabula.jar
...
ERROR: initialization failed
org.jruby.rack.RackInitializationException: undefined local variable or method `data_home' for TabulaSettings:Module
    from /tmp/jetty-0.0.0.0-8080-tabula.jar-_-any-1216581440460121418.dir/webapp/WEB-INF/webapp/tabula_settings.rb:49:in `getDataDir'
    from /tmp/jetty-0.0.0.0-8080-tabula.jar-_-any-1216581440460121418.dir/webapp/WEB-INF/webapp/tabula_settings.rb:78:in `TabulaSettings'
    from /tmp/jetty-0.0.0.0-8080-tabula.jar-_-any-1216581440460121418.dir/webapp/WEB-INF/webapp/tabula_settings.rb:4:in `(root)'
...
```

See https://github.com/tabulapdf/tabula/blob/master/webapp/tabula_settings.rb#L49 for the error. `data_home` is used instead of `home`

**Comment by olejorgenb** [comment]
A workaround is to start tabulu with `XDG_DATA_HOME` unset
