### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by organisergirl** [tabulapdf/tabula#430]
Started running tabula-win-1.0.1 on my computer.
OS is windows 7 enterprise SP 1, 64 bit
Java version 8 update 66 (just installed yesterday)
A browser doesn't open so I load up http://127.0.0.1:8080/ manually then the following message occurs:

No such process - \\userGH\H\hann0089\prefs\AppData\Tabula\pdfs from org/jruby/RubyDir.java:443:in `mkdir' from /C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:247:in `fu_mkdir' from /C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:221:in `mkdir_p' from org/jruby/RubyArray.java:1693:in `reverse_each' from /C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:219:in `mkdir_p' from org/jruby/RubyArray.java:1613:in `each' from /C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:205:in `mkdir_p' from C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/webapp/tabula_settings.rb:86:in `TabulaSettings' from C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/webapp/tabula_settings.rb:4:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from file:/C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1:in `(root)' from file:/C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24:in `require_relative' from org/jruby/RubyBasicObject.java:1533:in `instance_eval' from C:\Users\hann0089\AppData\Local\Temp\jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir\webapp\WEB-INF\config.ru:5:in `(root)' from C:/Users/hann0089/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-2109494470903787904.dir/webapp/WEB-INF/gems/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'

**Comment by jeremybmerrill** [comment]
yikes, this looks like a JRuby bug of some sort. I'll look into it... thank you for reporting!
