### ISSUE TITLE
Error: org.jruby.rack.RackInitializationException: No such file or directory

### ISSUE THREAD

**Issue by kbalint** [tabulapdf/tabula#462]
I've just installed Tabula 1.0.1, and the following happens (same as running from the exe or from command line from the readme.txt).

It seems like a weird error with accented characters in path: my user folder is under 'c:\Users\Bálint', which got translated to 'C:/Users/B?ílint':

`org.jruby.rack.RackInitializationException: No such file or directory - C:/Users/B?ílint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/krypt-provider-jdk-0.0.2.gemspec
	from org/jruby/RubyFile.java:361:in `initialize'
	from org/jruby/RubyIO.java:1177:in `open'
	from org/jruby/RubyKernel.java:349:in `open'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/stub_specification.rb:61:in `data'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/stub_specification.rb:109:in `valid?'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:687:in `each_stub'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:678:in `each_gemspec'
	from org/jruby/RubyArray.java:1613:in `each'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:677:in `each_gemspec'
	from org/jruby/RubyArray.java:1613:in `each'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:676:in `each_gemspec'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:685:in `each_stub'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:705:in `stubs'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:897:in `find_inactive_by_path'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems.rb:183:in `try_activate'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:132:in `require'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/rack_ext.rb:9:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
	from /C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
	from org/jruby/RubyBasicObject.java:1533:in `instance_eval'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack.rb:86:in `(root)'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:35:in `run_boot_hook'
	from org/jruby/RubyArray.java:1613:in `each'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:46:in `run_boot_hooks!'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:44:in `run_boot_hooks!'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:277:in `run_boot_hooks'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:100:in `boot!'
	from org/jruby/RubyKernel.java:1081:in `load'
	from file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/boot/rack.rb:10:in `(root)'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at WarMain.launchWebServer(WarMain.java:181)
	at WarMain.start(WarMain.java:355)
	at JarMain.doStart(JarMain.java:228)
	at WarMain.main(WarMain.java:378)
Caused by: org.jruby.exceptions.RaiseException: (Errno::ENOENT) C:/Users/B?ílint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/gems/shared/specifications/default/krypt-provider-jdk-0.0.2.gemspec
	at org.jruby.RubyFile.initialize(org/jruby/RubyFile.java:361)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1177)
	at org.jruby.RubyKernel.open(org/jruby/RubyKernel.java:349)
	at RUBY.data(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/stub_specification.rb:61)
	at RUBY.valid?(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/stub_specification.rb:109)
	at RUBY.each_stub(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:687)
	at RUBY.each_gemspec(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:678)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.each_gemspec(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:677)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.each_gemspec(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:676)
	at RUBY.each_stub(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:685)
	at RUBY.stubs(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:705)
	at RUBY.find_inactive_by_path(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:897)
	at RUBY.try_activate(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems.rb:183)
	at RUBY.require(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:132)
	at RUBY.(root)(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/rack_ext.rb:9)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
	at RUBY.(root)(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1)
	at RUBY.require(/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1533)
	at RUBY.(root)(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack.rb:86)
	at RUBY.run_boot_hook(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:35)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.run_boot_hooks!(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:46)
	at RUBY.run_boot_hooks!(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:44)
	at RUBY.run_boot_hooks(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:277)
	at RUBY.boot!(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/booter.rb:100)
	at org.jruby.RubyKernel.load(org/jruby/RubyKernel.java:1081)
	at RUBY.(root)(file:/C:/Users/Bálint/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-1845157071607107997.dir/webapp/WEB-INF/lib/jruby-rack-1.1.19.jar!/jruby/rack/boot/rack.rb:10)
`

**Comment by kbalint** [comment]
I was running it from c:\temp\tabula. (with everyone full control rights). it is a temp folder issue
