### ISSUE TITLE
Java class load error: com.ınfomatiq.jsi.rtree.RTree

### ISSUE THREAD

**Issue by ilden** [tabulapdf/tabula#464]
Hi,

I tried to use tabula on my ubuntu Ubuntu 14.04.4 LTS box with java version "1.7.0_95". But I got a java class error:

    NameError: cannot load Java class com.ınfomatiq.jsi.rtree.RTree

Terminal output logs, java build details and browser screenshot are below. What should I do?

Thanks.

Java details are:
```bash
den@lok:~/apps/tabula$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

And here is the terminal output: 
```bash
den@lok:~/apps/tabula$ java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -Dwarbler.port=9999 -jar tabula.jar
72016-02-17 21:29:44.650:INFO::main: Logging initialized @364ms
2016-02-17 21:29:44.668:INFO:oejr.Runner:main: Runner
2016-02-17 21:29:44.983:INFO:oejs.Server:main: jetty-9.2.9.v20150224


2016-02-17 21:30:02.985:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
INFO: jruby 1.7.15 (1.9.3p392) 2014-09-03 82b5cc3 on OpenJDK 64-Bit Server VM 1.7.0_95-b00 +jit [linux-amd64]
INFO: using a shared (threadsafe!) runtime
An exception happened during JRuby-Rack startup
cannot load Java class com.ınfomatiq.jsi.rtree.RTree
--- System
jruby 1.7.15 (1.9.3p392) 2014-09-03 82b5cc3 on OpenJDK 64-Bit Server VM 1.7.0_95-b00 +jit [linux-amd64]
Time: 2016-02-17 21:30:16 +0200
Server: jetty/9.2.9.v20150224
jruby.home: file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home

--- Context Init Parameters:
jruby.compat.version = 1.9
jruby.rack.logging = stderr
public.root = /
rack.env = production

--- Backtrace
NameError: cannot load Java class com.ınfomatiq.jsi.rtree.RTree
          for_name at org/jruby/javasupport/JavaClass.java:1286
   get_proxy_class at org/jruby/javasupport/JavaUtilities.java:34
     const_missing at file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/java/java_package_module_template.rb:4
            Tabula at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities/text_element_index.rb:2
            (root) at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities/text_element_index.rb:1
           require at org/jruby/RubyKernel.java:1065
            (root) at file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1
  require_relative at file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24
           require at org/jruby/RubyKernel.java:1065
            (root) at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities.rb:6
            (root) at file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1
           require at org/jruby/RubyKernel.java:1065
  require_relative at file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24
              each at org/jruby/RubyArray.java:1613
            (root) at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula.rb:18
              each at org/jruby/RubyArray.java:1613
            (root) at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:1
           require at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:76
           require at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:72
     instance_eval at org/jruby/RubyBasicObject.java:1533
           require at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:61
           require at /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler.rb:134

--- RubyGems
Gem.dir: /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems
Gem.path:
/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems
Activated gems:
  rack-1.5.2
  bundler-1.10.6
  cuba-3.3.0
  trollop-2.1.2
  tabula-extractor-0.8.0-java
  tilt-2.0.1

--- Bundler
Bundler.bundle_path: /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems
Bundler.root: /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF
Gemfile: /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/Gemfile
Settings:
  gemfile = /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/Gemfile
  without = development:test:assets
  bin_path = /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/bin/bundle

--- JRuby-Rack Config
compat_version = RUBY1_9
default_logger = org.jruby.rack.logging.StandardOutLogger@6790ec8c
equals = <error: >
err = java.io.PrintStream@f1be122
filter_adds_html = true
filter_verifies_resource = false
ignore_environment = false
initial_memory_buffer_size = 
initial_runtimes = 
jms_connection_factory = 
jms_jndi_properties = 
logger = org.jruby.rack.logging.OutputStreamLogger@5ea96ab7
logger_class_name = stderr
logger_name = jruby.rack
maximum_memory_buffer_size = 
maximum_runtimes = 
num_initializer_threads = 
out = java.io.PrintStream@d99bef1
rackup = 
rackup_path = 
rewindable = true
runtime_arguments = 
runtime_environment = 
runtime_timeout_seconds = 
serial_initialization = false
servlet_context = ServletContext@o.e.j.w.WebAppContext@2b578c61{/,file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/,STARTING}{file:/home/den/apps/tabula/tabula.jar}
throw_init_exception = false
ERROR: initialization failed
org.jruby.rack.RackInitializationException: cannot load Java class com.ınfomatiq.jsi.rtree.RTree
	from org/jruby/javasupport/JavaClass.java:1286:in `for_name'
	from org/jruby/javasupport/JavaUtilities.java:34:in `get_proxy_class'
	from file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/java/java_package_module_template.rb:4:in `const_missing'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities/text_element_index.rb:2:in `Tabula'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities/text_element_index.rb:1:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
	from file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1:in `(root)'
	from file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24:in `require_relative'
	from org/jruby/RubyKernel.java:1065:in `require'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities.rb:6:in `(root)'
	from file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1:in `(root)'
	from org/jruby/RubyKernel.java:1065:in `require'
	from file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24:in `require_relative'
	from org/jruby/RubyArray.java:1613:in `each'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula.rb:18:in `(root)'
	from org/jruby/RubyArray.java:1613:in `each'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:1:in `(root)'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `require'
	from org/jruby/RubyBasicObject.java:1533:in `instance_eval'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'

	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at WarMain.launchWebServer(WarMain.java:181)
	at WarMain.start(WarMain.java:355)
	at JarMain.doStart(JarMain.java:228)
	at WarMain.main(WarMain.java:378)
Caused by: org.jruby.exceptions.RaiseException: (NameError) cannot load Java class com.ınfomatiq.jsi.rtree.RTree
	at org.jruby.javasupport.JavaClass.for_name(org/jruby/javasupport/JavaClass.java:1286)
	at org.jruby.javasupport.JavaUtilities.get_proxy_class(org/jruby/javasupport/JavaUtilities.java:34)
	at RUBY.const_missing(file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/java/java_package_module_template.rb:4)
	at RUBY.Tabula(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities/text_element_index.rb:2)
	at RUBY.(root)(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities/text_element_index.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
	at RUBY.(root)(file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1)
	at RUBY.require_relative(file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
	at RUBY.(root)(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula/entities.rb:6)
	at RUBY.(root)(file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1065)
	at RUBY.require_relative(file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.(root)(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/tabula-extractor-0.8.0-java/lib/tabula.rb:18)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.(root)(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:1)
	at RUBY.require(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:76)
	at RUBY.require(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:72)
	at org.jruby.RubyBasicObject.instance_eval(org/jruby/RubyBasicObject.java:1533)
	at RUBY.require(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler/runtime.rb:61)
	at RUBY.require(/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/WEB-INF/gems/gems/bundler-1.10.6/lib/bundler.rb:134)
2016-02-17 21:30:17.334:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2b578c61{/,file:/tmp/jetty-0.0.0.0-9999-tabula.jar-_-any-7850093423477022705.dir/webapp/,AVAILABLE}{file:/home/den/apps/tabula/tabula.jar}
2016-02-17 21:30:17.335:WARN:oejsh.RequestLogHandler:main: !RequestLog
2016-02-17 21:30:17.381:INFO:oejs.ServerConnector:main: Started ServerConnector@286ee8d5{HTTP/1.1}{0.0.0.0:9999}
2016-02-17 21:30:17.382:INFO:oejs.Server:main: Started @33102ms
```

![internal_server_error](https://cloud.githubusercontent.com/assets/17301342/13123814/cc6254da-d5c6-11e5-948d-75478a407806.png)

**Comment by jeremybmerrill** [comment]
I presume your computer is set to Turkish? (Or something else with the character `ı` along with `i`?)

Anyways, I'm not immediately sure of a solution, but the problem is that `com.ınfomatiq.jsi.rtree.RTree` should be `com.infomatiq.jsi.rtree.RTree` -- that is, that a  `ı` has shown up where `i` ought to be.

Does that sound familiar as a problem you've seen before?

**Comment by ilden** [comment]
It seems that you are right. The problem is "ı". But I did not specify "ı" anywhere. I just downloaded, extracted and run. And any of parameters didn't contain "ı". 

```bash
den@lok:~/apps/tabula$ java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -Dwarbler.port=9999 -jar tabula.jar
```

Is there any env var or something like which I should set?

**Comment by jeremybmerrill** [comment]
I don't know. I'll have to do some research. I'll let you know what I find.
(It is Turkish, right? I think that'll help me in my research.)

**Comment by ilden** [comment]
Sorry... I see your reply now. Yes my computer is set Turkish

**Comment by ilden** [comment]
You are right. I set the language of my computer to English and then I was able to run Tabula.

**Comment by ilden** [comment]
You are right. I set the language of my computer to English and then I was able to run Tabula.

**Comment by jazzido** [comment]
Thanks for letting us know, @ilden. This is useful information.

You might also be able to run Tabula without switching the computer's locale by following these steps:
- Open a Command Prompt
- type `cd` and then the path to the directory that contains tabula.exe, e.g. `cd C:\Users\Username\Downloads`
- Change that terminal's codepage to Unicode by typing: `chcp 65001`
- Run Tabula by typing `tabula.exe`

**Comment by oguzhanogreden** [comment]
@jazzido is it expected/possible that this solution will fail in Windows 10? Although `chcp 65001` returns `Active code page: 65001` it does not seem to solve this issue. Unfortunately I can't switch my system language due to a OEM Single Language version of Windows 10.

**Comment by jazzido** [comment]
Hi @oguzhanogreden,

Unfortunately, I don't have access to a single-language Windows 10 machine, nor I'm very familiar with their implementation of i18n/l10n.

Are you getting the same error message that is described on this issue?

**Comment by oguzhanogreden** [comment]
Yes I'm getting the same error due to 'ı' in `com.ınfomatiq.jsi.rtree.RTree`. I forgot to mention, my system is also Turkish.

I'll write if I can fix it then. Thanks!
