### ISSUE TITLE
java.lang.NullPointerException on Ubuntu install

### ISSUE THREAD

**Issue by msoares** [tabulapdf/tabula#500]
Hi. I'm trying to install Tabula on Ubuntu 14.04. I'm quite new to Ubuntu, so for some time I'll be needing step-by-step advice on how to do things on terminal. 

I've downloaded and expanded the Tabula zip elements onto a folder of its own. Then I went to that folder in Terminal and pasted the code described on readme:

`java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -Dwarbler.port=8080 -jar tabula.jar`

This is the feedback I got:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jetty/runner/Runner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at WarMain.launchWebServer(WarMain.java:177)
	at WarMain.start(WarMain.java:355)
	at JarMain.doStart(JarMain.java:228)
	at WarMain.main(WarMain.java:378)
ERROR: java.lang.NullPointerException
```

What am I doing wrong?

**Comment by melisabok** [comment]
Which java version are you using? You can do java -version in the console.

**Comment by msoares** [comment]
This was the result:

```
java version "1.6.0_38"
OpenJDK Runtime Environment (IcedTea6 1.13.10) (6b38-1.13.10-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

```

**Comment by jazzido** [comment]
Thanks, @msoares — Tabula needs Java 1.7+.
You can install it on Ubuntu 14.04 with: `sudo apt-get install openjdk-7-jre`

**Comment by msoares** [comment]
Thank you, jazzido and melisabok!
