### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by geniusjoa** [tabulapdf/tabula#531]
Hi, run tabula in SO Windows 8.1 and Java JJre-8u101 64bits. Error program.

-----------------------------------------------------------------------------------------------------------------

Internal Server Error (500)
Request Method:	GET
Request URL:	http://localhost:8080/

No such process - \\SMM-CCS-DC01\Perfiles\Locales\joan.garcia\Datos de programa\Tabula\pdfs from org/jruby/RubyDir.java:443:in `mkdir' from /C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:247:in `fu_mkdir' from /C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:221:in `mkdir_p' from org/jruby/RubyArray.java:1693:in `reverse_each' from /C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:219:in `mkdir_p' from org/jruby/RubyArray.java:1613:in `each' from /C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/lib/jruby-stdlib-complete-1.7.15.jar!/META-INF/jruby.home/lib/ruby/1.9/fileutils.rb:205:in `mkdir_p' from C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/webapp/tabula_settings.rb:86:in `TabulaSettings' from C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/webapp/tabula_settings.rb:4:in `(root)' from org/jruby/RubyKernel.java:1065:in `require' from file:/C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:1:in `(root)' from file:/C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/lib/jruby-core-complete-1.7.15.jar!/jruby/kernel19/kernel.rb:24:in `require_relative' from org/jruby/RubyBasicObject.java:1533:in `instance_eval' from C:\Users\joan.garcia\AppData\Local\Temp\jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir\webapp\WEB-INF\config.ru:5:in `(root)' from C:/Users/joan.garcia/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-5705691456279457813.dir/webapp/WEB-INF/gems/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.

Thank.

**Comment by massimosala** [comment]
Same here, trying on tow pc : Windows 7 SP 1 and Windows XP SP3. The error is 500 but on these pc it starts with "Could not load FFI provider." Solved running Tabula under Administrator ( logged user isn't into Administrators group ). Please can you confirm, is it mandatory ?

**Comment by massimosala** [comment]
I don't like the solution "run as Administrator". The tabula directories are writeable by all the users. Waht cn I do ? The error is about FFI : I download [libjffi 1.2](https://github.com/jnr/jffi/blob/master/archive/jffi-i386-Windows.jar) and put the DLL where is tabula.jar : problem fixed.
