### ISSUE TITLE
Unable to convert chead042.pdf

### ISSUE THREAD

**Issue by howawong** [tabulapdf/tabula#577]
Source: http://www.budget.gov.hk/2016/chi/pdf/chead042.pdf

Web Browser:
![capture](https://cloud.githubusercontent.com/assets/760880/19831026/0f43bafc-9e33-11e6-9da1-55217e2b4ccc.PNG)

Console:
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BDC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: EMC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: i
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BDC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: EMC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: i
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BDC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: EMC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: i
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: BDC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: EMC
Oct 29, 2016 11:52:33 PM org.apache.pdfbox.util.PDFStreamEngine processOperator
INFO: unsupported/disabled operation: i

**Comment by jeremybmerrill** [comment]
I'm pretty sure this is just a PDFBox issue. A fix will have to wait until PDFBox 2.0 integration is finished. Do you agree, @jazzido ?

````
WARNING: java.lang.NullPointerException
java.lang.NullPointerException
	at technology.tabula.ObjectExtractor.fillPath(ObjectExtractor.java:283)
	at org.apache.pdfbox.util.operator.pagedrawer.FillEvenOddRule.process(FillEvenOddRule.java:57)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:269)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:236)
	at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:216)
	at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
	at technology.tabula.PageIterator.next(PageIterator.java:29)
	at technology.tabula.PageIterator.next(PageIterator.java:6)
````
