### ISSUE TITLE
warn users with old Java

### ISSUE THREAD

**Issue by jeremybmerrill** [tabulapdf/tabula#585]
apparently there are some bugs like this if you have Java 1.6 (e.g. on a Mac)
````
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Integer.compare(II)I
	at technology.tabula.TextChunk.isLtrDominant(TextChunk.java:179)
	at technology.tabula.TextElement.mergeWords(TextElement.java:266)
	at technology.tabula.TextElement.mergeWords(TextElement.java:105)
````

**Comment by jazzido** [comment]
We should compile it so it doesn't generate 1.6 compatible bytecode.

**Comment by jeremybmerrill** [comment]
sounds like a good solution to me (then Java would say 'You've gotta upgrade to run this'?)

**Comment by jazzido** [comment]
I don't think so, but it'll refuse to start the app.

**Comment by jeremybmerrill** [comment]
That'd certainly work for me.

**Comment by jeremybmerrill** [comment]
@mtigas: Is this something you'd do in the build step?
