### ISSUE TITLE
Tabula couldn't finish processing your request

### ISSUE THREAD

**Issue by nk9** [tabulapdf/tabula#588]
**Link to the offending document:**
[PDF](http://www.co.hood-river.or.us/vertical/sites/%7B4BB5BFDA-3709-449E-9B16-B62A0A0DD6E4%7D/uploads/%7BD592B8D7-A0A9-4A14-9D88-61AFC22E3533%7D.PDF)

**Error:**
Tabula API version: 1.1.0.16092117
Filename: {D592B8D7-A0A9-4A14-9D88-61AFC22E3533}.PDF
Internal Server Error (500)
    
      
        Request Method:
        POST
      
      
        Request URL:
        http://127.0.0.1:8080/pdf/a0eaf2ddcff8b788c75058540f04e07a2a403c42/data

**Comment by jeremybmerrill** [comment]
Hi @nk9:

I downloaded the document and it worked for me. Can you give me more information on what you were selecting (which page or which race's results, approximately what area, etc.)?

I did notice an error in extraction, but it didn't cause a 500 for me:
````
Nov 23, 2016 8:04:29 PM org.apache.pdfbox.util.operator.pagedrawer.FillNonZeroRule process
WARNING: java.lang.NullPointerException
java.lang.NullPointerException
	at technology.tabula.ObjectExtractor.fillPath(ObjectExtractor.java:283)
	at org.apache.pdfbox.util.operator.pagedrawer.FillNonZeroRule.process(FillNonZeroRule.java:58)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:562)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:269)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:236)
	at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:216)
	at technology.tabula.ObjectExtractor.drawPage(ObjectExtractor.java:153)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:108)
````

**Comment by nk9** [comment]
I was able to get it working by limiting the number of selections to the first 20 pages and selecting them manually. But here's how to reproduce it with the above PDF:

1. Create 2 selections on the first page.
2. Click "Repeat this Selection" both times.
3. Click Preview & Export

The selections will indeed repeat, but towards the end they'll get all jumbled. Some pages are blank, while other pages contain overlapping selections.

**Comment by jeremybmerrill** [comment]
Hi @nk9: 

Thanks! I was able to replicate; we'll look into the bug. And I'm glad you were able to get it working. The backtrace includes the backtrace above six times (but nothing specifically error-related).
