### ISSUE TITLE
Tabula open problem

### ISSUE THREAD

**Issue by Harrieeeett** [tabulapdf/tabula#828]
Hi, I have just downloaded Java 8 and Tabula-win-1.2.0. But when I double click on the program, these words shown on my Microsoft Edge browser. BTW,my system is win 10.

"org.jruby.rack.RackInitializationException: no such file to load -- bundler/shared_helpers from org/jruby/RubyKernel.java:955:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require' from file:/C:/Users/%E6%96%B9%E8%8A%B7%E8%90%B1/AppData/Local/Temp/jetty-0.0.0.0-8080-tabula.jar-_-any-142615044296297151.dir/webapp/META-INF/init.rb:29:in `' from org/jruby/RubyKernel.java:994:in `eval' from uri:classloader:/jruby/rack/booter.rb:256:in `block in load_settings_from_init_rb' from org/jruby/RubyArray.java:1735:in `each' from uri:classloader:/jruby/rack/booter.rb:243:in `load_settings_from_init_rb' from uri:classloader:/jruby/rack/booter.rb:99:in `boot!' from uri:classloader:/jruby/rack/boot/rack.rb:10:in `
' from org/jruby/RubyKernel.java:973:in `load' from "

Please help, thanks!

**Comment by Harrieeeett** [comment]
It now turn to sth like this:

Internal Server Error (500)
Request Method: | GET
Request URL: | http://127.0.0.1:8080/
(TypeError) no implicit conversion from nil to integer
You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.

**Comment by jcristovao** [comment]
Did you manage to solve this? I'm having a similar problem (to the first post)

**Comment by 0parth** [comment]
Hello. I had the same problem. Try to clear the temp folder. 
It worked for me.

**Comment by AlexDeat** [comment]
Having the Same Problem!

**Comment by AlexDeat** [comment]
(ParserError) A JSON text must at least contain two octets!

You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.
