### ISSUE TITLE
Non-parseable POM error

### ISSUE THREAD

**Issue by TonyGan329** [tabulapdf/tabula#882]
I have run into 'Non-parseable POM' error with the latest Jbundler 0.9.3 version when running Tabula from source code.

Here is the output of `bundle exec jbundle install --debug`

```
mvn dependency:list -f C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/dependency_pom.rb -Dverbose=true -X -DexcludeTransitive=true -Djbundler.outputFile=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/pkg/dependencies.txt -Djbundler.basedir=C:/Users/tony.gan/Downloads/tabula-master/tabula-master -Djbundler.jarfile=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/Jarfile -Djbundler.gemfile=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/Gemfile -Djbundler.workdir=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/pkg -Djbundler.groups -Djbundler.bootstrap -Dmaven.repo.local=C:\Users\tony.gan/.m2/repository
mvn dependency:list -f C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/dependency_pom.rb -Dverbose=true -X -DexcludeTransitive=true -Djbundler.outputFile=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/pkg/dependencies.txt -Djbundler.basedir=C:/Users/tony.gan/Downloads/tabula-master/tabula-master -Djbundler.jarfile=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/Jarfile -Djbundler.gemfile=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/Gemfile -Djbundler.workdir=C:/Users/tony.gan/Downloads/tabula-master/tabula-master/pkg -Djbundler.groups -Djbundler.bootstrap -Dmaven.repo.local=C:\Users\tony.gan/.m2/repository
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\ruby-maven-libs-3.3.9\maven-home
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: c:\program files\java\jre1.8.0_171
Default locale: en_US, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
[DEBUG] Reading global settings from C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\ruby-maven-libs-3.3.9\maven-home\conf\settings.xml
[DEBUG] Reading user settings from C:\Users\tony.gan\.m2\settings.xml
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for C:\Users\tony.gan\.m2\repository
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/torquebox/mojo/mavengem-wagon/0.2.1/mavengem-wagon-0.2.1.pom
[DEBUG] Writing tracking file C:\Users\tony.gan\.m2\repository\org\torquebox\mojo\mavengem-wagon\0.2.1\mavengem-wagon-0.2.1.pom.lastUpdated
[WARNING] Failed to read extensions descriptor C:\Users\tony.gan\Downloads\tabula-master\tabula-master\.mvn\extensions.xml: Plugin org.torquebox.mojo:mavengem-wagon:0.2.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.torquebox.mojo:mavengem-wagon:jar:0.2.1
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\ruby-maven-libs-3.3.9\maven-home\conf\settings.xml
[DEBUG] Reading user settings from C:\Users\tony.gan\.m2\settings.xml
[DEBUG] Reading global toolchains from C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\ruby-maven-libs-3.3.9\maven-home\conf\toolchains.xml
[DEBUG] Reading user toolchains from C:\Users\tony.gan\.m2\toolchains.xml
[DEBUG] Using local repository at C:\Users\tony.gan\.m2\repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for C:\Users\tony.gan\.m2\repository
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\jbundler-0.9.3\lib\jbundler\dependency_pom.rb: only whitespace content allowed before start tag and not b (position: START_DOCUMENT seen b... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\jbundler-0.9.3\lib\jbundler\dependency_pom.rb: only whitespace content allowed before start tag and not b (position: START_DOCUMENT seen b... @1:1)  @ line 1, column 1

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR]   The project  (C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\jbundler-0.9.3\lib\jbundler\dependency_pom.rb) has 1 error
[ERROR]     Non-parseable POM C:\jruby-9.1.15.0\lib\ruby\gems\shared\gems\jbundler-0.9.3\lib\jbundler\dependency_pom.rb: only whitespace content allowed before start tag and not b (position: START_DOCUMENT seen b... @1:1)  @ line 1, column 1 -> [Help 2]
org.apache.maven.model.io.ModelParseException: only whitespace content allowed before start tag and not b (position: START_DOCUMENT seen b... @1:1)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:122)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:86)
        at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:81)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:533)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:273)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: only whitespace content allowed before start tag and not b (position: START_DOCUMENT seen b... @1:1)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1557)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1436)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4392)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:598)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:113)
        ... 25 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
Errno::ENOENT: No such file or directory - C:/Users/tony.gan/Downloads/tabula-master/tabula-master/pkg/dependencies.txt
                  read at org/jruby/RubyIO.java:3673
  install_dependencies at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/lock_down.rb:113
             lock_down at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/lock_down.rb:54
               install at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/cli.rb:80
                   run at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27
        invoke_command at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
              dispatch at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387
                 start at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466
                <main> at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/bin/jbundle:47
                  load at org/jruby/RubyKernel.java:973
                <main> at c:\jruby-9.1.15.0\bin\jbundle:23
```

Any idea on how to fix this?

**Comment by jeremybmerrill** [comment]
I'm not able to reproduce it on Linux. Maybe this is Windows related?

**Comment by TonyGan329** [comment]
I have tried another computer and it can work. Maybe the network issues...
