### ISSUE TITLE
"Sorry, your file upload could not be processed. Please double-check that the file you uploaded is a valid PDF file and try again."

### ISSUE THREAD

**Issue by guterj** [tabulapdf/tabula#955]
First time I used it worked perfectly. But now, even the same pdf I converted earlier I can't convert anymore.
Apparently it is Java heap space. Dow anyone knows how to help me?!

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap s
pace
        at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTas
k)
        at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(or
g/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/J
avaMethod.java:302)
        at RUBY.afterExecute(C:/Users/gguterre/AppData/Local/Temp/jetty-0.0.0.0-
8080-tabula.jar-_-any-4862543889552294438.dir/webapp/WEB-INF/lib/tabula_job_exec
utor/executor.rb:42)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.java.util.concurrent.ThreadPoolExecutor$Proxy1.afterE
xecute(org/jruby/proxy/java/util/concurrent/ThreadPoolExecutor$Proxy1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurren
t/ThreadPoolExecutor)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurre
nt/ThreadPoolExecutor$Worker)
        at java.lang.Thread.run(java/lang/Thread)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.jruby.util.ByteList.ensure(ByteList.java:341)
        at org.jruby.util.io.EncodingUtils$1.resize(EncodingUtils.java:1197)
        at org.jruby.util.io.EncodingUtils.moreOutputBuffer(EncodingUtils.java:1
513)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1415
)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1312
)
        at org.jruby.util.io.EncodingUtils.strTranscode0(EncodingUtils.java:936)

        at org.jruby.util.io.EncodingUtils.strTranscode(EncodingUtils.java:857)
        at org.jruby.util.io.EncodingUtils.strEncode(EncodingUtils.java:829)
        at org.jruby.RubyString.encode(RubyString.java:5398)
        at json.ext.Parser.convertEncoding(Parser.java:196)
        at json.ext.Parser.initialize(Parser.java:175)
        at json.ext.Parser$INVOKER$i$0$1$initialize.call(Parser$INVOKER$i$0$1$in
itialize.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMe
thod.java:725)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:208)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMe
thod.java:741)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
77)
        at org.jruby.RubyObject.callInit(RubyObject.java:348)
        at json.ext.Parser.newInstance(Parser.java:151)
        at json.ext.Parser$INVOKER$s$0$1$newInstance.call(Parser$INVOKER$s$0$1$n
ewInstance.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:212)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:208)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
181)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEng
ine.java:324)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupIn
terpreterEngine.java:74)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngin
e.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD
(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIR
Method.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:200)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
153)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEng
ine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupIn
terpreterEngine.java:74)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java
:132)
nov 30, 2018 10:30:01 AM org.apache.pdfbox.cos.COSDocument finalize
ADVERT├èNCIA: Warning: You did not close a PDF Document
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap s
pace
        at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTas
k)
        at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(or
g/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/J
avaMethod.java:302)
        at RUBY.afterExecute(C:/Users/gguterre/AppData/Local/Temp/jetty-0.0.0.0-
8080-tabula.jar-_-any-4862543889552294438.dir/webapp/WEB-INF/lib/tabula_job_exec
utor/executor.rb:42)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.java.util.concurrent.ThreadPoolExecutor$Proxy1.afterE
xecute(org/jruby/proxy/java/util/concurrent/ThreadPoolExecutor$Proxy1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurren
t/ThreadPoolExecutor)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurre
nt/ThreadPoolExecutor$Worker)
        at java.lang.Thread.run(java/lang/Thread)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.jruby.util.ByteList.ensure(ByteList.java:341)
        at org.jruby.util.io.EncodingUtils$1.resize(EncodingUtils.java:1197)
        at org.jruby.util.io.EncodingUtils.moreOutputBuffer(EncodingUtils.java:1
513)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1415
)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1312
)
        at org.jruby.util.io.EncodingUtils.strTranscode0(EncodingUtils.java:936)

        at org.jruby.util.io.EncodingUtils.strTranscode(EncodingUtils.java:857)
        at org.jruby.util.io.EncodingUtils.strEncode(EncodingUtils.java:829)
        at org.jruby.RubyString.encode(RubyString.java:5398)
        at json.ext.Parser.convertEncoding(Parser.java:196)
        at json.ext.Parser.initialize(Parser.java:175)
        at json.ext.Parser$INVOKER$i$0$1$initialize.call(Parser$INVOKER$i$0$1$in
itialize.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMe
thod.java:725)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:208)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMe
thod.java:741)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
77)
        at org.jruby.RubyObject.callInit(RubyObject.java:348)
        at json.ext.Parser.newInstance(Parser.java:151)
        at json.ext.Parser$INVOKER$s$0$1$newInstance.call(Parser$INVOKER$s$0$1$n
ewInstance.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:212)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:208)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
181)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEng
ine.java:324)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupIn
terpreterEngine.java:74)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngin
e.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD
(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIR
Method.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:200)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
153)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEng
ine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupIn
terpreterEngine.java:74)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java
:132)
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap s
pace
        at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTas
k)
        at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(or
g/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/J
avaMethod.java:302)
        at RUBY.afterExecute(C:/Users/gguterre/AppData/Local/Temp/jetty-0.0.0.0-
8080-tabula.jar-_-any-4862543889552294438.dir/webapp/WEB-INF/lib/tabula_job_exec
utor/executor.rb:42)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.java.util.concurrent.ThreadPoolExecutor$Proxy1.afterE
xecute(org/jruby/proxy/java/util/concurrent/ThreadPoolExecutor$Proxy1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurren
t/ThreadPoolExecutor)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurre
nt/ThreadPoolExecutor$Worker)
        at java.lang.Thread.run(java/lang/Thread)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.jruby.util.ByteList.ensure(ByteList.java:341)
        at org.jruby.util.io.EncodingUtils$1.resize(EncodingUtils.java:1197)
        at org.jruby.util.io.EncodingUtils.moreOutputBuffer(EncodingUtils.java:1
513)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1415
)
        at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:1312
)
        at org.jruby.util.io.EncodingUtils.strTranscode0(EncodingUtils.java:936)

        at org.jruby.util.io.EncodingUtils.strTranscode(EncodingUtils.java:857)
        at org.jruby.util.io.EncodingUtils.strEncode(EncodingUtils.java:829)
        at org.jruby.RubyString.encode(RubyString.java:5398)
        at json.ext.Parser.convertEncoding(Parser.java:196)
        at json.ext.Parser.initialize(Parser.java:175)
        at json.ext.Parser$INVOKER$i$0$1$initialize.call(Parser$INVOKER$i$0$1$in
itialize.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMe
thod.java:725)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:208)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMe
thod.java:741)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
77)
        at org.jruby.RubyObject.callInit(RubyObject.java:348)
        at json.ext.Parser.newInstance(Parser.java:151)
        at json.ext.Parser$INVOKER$s$0$1$newInstance.call(Parser$INVOKER$s$0$1$n
ewInstance.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:212)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:208)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
181)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEng
ine.java:324)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupIn
terpreterEngine.java:74)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngin
e.java:84)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD
(MixedModeIRMethod.java:179)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIR
Method.java:165)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:200)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
153)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEng
ine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupIn
terpreterEngine.java:74)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java
:132)
nov 30, 2018 10:31:17 AM org.apache.pdfbox.cos.COSDocument finalize
ADVERT├èNCIA: Warning: You did not close a PDF Document
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap s
pace
        at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTas
k)
        at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(or
g/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/J
avaMethod.java:302)
        at RUBY.afterExecute(C:/Users/gguterre/AppData/Local/Temp/jetty-0.0.0.0-
8080-tabula.jar-_-any-4862543889552294438.dir/webapp/WEB-INF/lib/tabula_job_exec
utor/executor.rb:42)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.java.util.concurrent.ThreadPoolExecutor$Proxy1.afterE
xecute(org/jruby/proxy/java/util/concurrent/ThreadPoolExecutor$Proxy1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurren
t/ThreadPoolExecutor)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurre
nt/ThreadPoolExecutor$Worker)
        at java.lang.Thread.run(java/lang/Thread)
Caused by: java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap s
pace
        at java.util.concurrent.FutureTask.report(java/util/concurrent/FutureTas
k)
        at java.util.concurrent.FutureTask.get(java/util/concurrent/FutureTask)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(or
g/jruby/javasupport/JavaMethod.java:438)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/J
avaMethod.java:302)
        at RUBY.afterExecute(C:/Users/gguterre/AppData/Local/Temp/jetty-0.0.0.0-
8080-tabula.jar-_-any-4862543889552294438.dir/webapp/WEB-INF/lib/tabula_job_exec
utor/executor.rb:42)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
        at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHand
ler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
        at org.jruby.proxy.java.util.concurrent.ThreadPoolExecutor$Proxy1.afterE
xecute(org/jruby/proxy/java/util/concurrent/ThreadPoolExecutor$Proxy1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurren
t/ThreadPoolExecutor)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurre
nt/ThreadPoolExecutor$Worker)
        at java.lang.Thread.run(java/lang/Thread)
Caused by: java.lang.OutOfMemoryError: Java heap space
nov 30, 2018 10:35:18 AM org.apache.pdfbox.cos.COSDocument finalize
ADVERT├èNCIA: Warning: You did not close a PDF Document
2018-11-30 10:35:23.679:WARN:oejs.ServletHandler:qtp265996-36: Error for /docume
nts
java.lang.OutOfMemoryError: Java heap space

**Comment by jeremybmerrill** [comment]
> the problem is solved!
> I had to delete the pdf files in tabula file from Appdata. 
> 
> Sorry for anything and thanks for Tabula! =D
>
