### ISSUE TITLE
Installation on Mac Error 500 JRuby

### ISSUE THREAD

**Issue by clbgit** [tabulapdf/tabula#987]
After installing on Mac running 10.13.6, the Tabula WarMain launches, but I get his error in browsers: 

Internal Server Error (500)
Request Method: | GET
Request URL:http://127.0.0.1:8080/

load error: /private/var/folders/3t/zyrk6055621fm2ygr9qqlkb80000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-6618728497949623376.dir/webapp/WEB-INF/lib/thumbnail_generator -- java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.github.jaiimageio.jpeg2000.impl.J2KImageReaderSpi could not be instantiated from org/jruby/RubyKernel.java:955:in `require' from uri:classloader:/jruby/kernel/kernel.rb:13:in `require_relative' from /private/var/folders/3t/zyrk6055621fm2ygr9qqlkb80000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-6618728497949623376.dir/webapp/WEB-INF/lib/tabula_job_executor/jobs/generate_thumbnails.rb:2:in `<main>' from org/jruby/RubyKernel.java:955:in `require' from uri:classloader:/jruby/kernel/kernel.rb:1:in `(root)' from uri:classloader:/jruby/kernel/kernel.rb:13:in `<main>' from org/jruby/RubyKernel.java:955:in `require' from /private/var/folders/3t/zyrk6055621fm2ygr9qqlkb80000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-6618728497949623376.dir/webapp/WEB-INF/webapp/tabula_web.rb:28:in `(root)' from uri:classloader:/jruby/kernel/kernel.rb:1:in `block in (root)' from org/jruby/RubyBasicObject.java:1691:in `instance_eval' from uri:classloader:/jruby/kernel/kernel.rb:13:in `require_relative' from /private/var/folders/3t/zyrk6055621fm2ygr9qqlkb80000gn/T/jetty-0.0.0.0-8080-tabula.jar-_-any-6618728497949623376.dir/webapp/WEB-INF/config.ru:14:in `<main>'

You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.

Thank you.

**Comment by bindu-josyula** [comment]
I am having the same issue with Tabula installed on Windows
